version: '3.5'
services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./docker/php.Dockerfile
    volumes:
      - .:/var/www/html
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /app
    volumes:
      - .:/app:rw
    networks:
      - app-network
  db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: myUserPass
        MYSQL_DATABASE: mydb
        MYSQL_USER: myUser
        MYSQL_PASSWORD: myUser
      networks:
      - app-network

  phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - 8088:80
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: myUserPass
      networks:
      - app-network
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
      - .:/app:rw
      - ./docker/default.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge